### ISSUE TITLE
Centralized control

### ISSUE THREAD

**Issue by andreycostalopes** [NREL/PyDSS#90]
Greetings. PyDSS presents in its structure a good hierarchy of classes for local control of several DERs. However, I haven't found a framework that works with centralized control. Is it possible to implement such a structure in PyDSS? How can it be implemented?

**Comment by AadilLatif** [comment]
Hi, yes it can. you would need to extend the abstract postprocess class rather than the abstract controller class and write a post-process script. We have implemented multiple coordination-based controls using the approach. Alternately, you can use the HELICS interface to communicate with an external controller. Both approaches have been tested and work
